import type { Resource, RouteMode, RouteOption } from "@/types/goodbois";

export const kioskLocation = {
  latitude: 1.28741,
  longitude: 103.83924,
  label: {
    en: "GoodBois kiosk at Jalan Kukoh void deck",
    "zh-Hans": "惹兰古谷组屋楼下 GoodBois 服务亭",
    "nan-Hant": "GoodBois kiosk at Jalan Kukoh void deck",
    ms: "Kios GoodBois di kolong Jalan Kukoh",
    ta: "ஜாலான் குகோ void deck GoodBois நிலையம்",
  },
};

const timestamps = {
  createdAt: "2026-05-09T00:00:00+08:00",
  updatedAt: "2026-05-10T00:00:00+08:00",
};

export const demoResources: Resource[] = [
  {
    id: "active-ageing-centre-jalan-kukoh",
    linkedAgencyKey: "active_ageing_centre_jalan_kukoh",
    name: {
      en: "Chinatown Active Ageing Centre (Jalan Kukoh)",
      "zh-Hans": "牛车水乐龄活动中心（惹兰古谷）",
      ms: "Pusat Penuaan Aktif Chinatown (Jalan Kukoh)",
      ta: "சைனாடவுன் செயலில் முதுமை மையம் (ஜாலான் குகோ)",
    },
    category: "senior_activity",
    description: {
      en: "Nearby active ageing centre for activities, befriending and light support.",
      "zh-Hans": "附近的乐龄活动中心，提供活动、陪伴和轻度支援。",
      ms: "Pusat warga emas berdekatan untuk aktiviti, teman berbual dan sokongan ringan.",
      ta: "செயற்பாடுகள், நட்பு ஆதரவு மற்றும் லேசான உதவிக்கான அருகிலுள்ள மையம்.",
    },
    address: {
      en: "8 Jalan Kukoh, #04-35, Singapore 162008",
      "zh-Hans": "惹兰古谷 8 号 #04-35，新加坡 162008",
      ms: "8 Jalan Kukoh, #04-35, Singapura 162008",
      ta: "8 ஜாலான் குகோ, #04-35, சிங்கப்பூர் 162008",
    },
    latitude: 1.287377626822412,
    longitude: 103.8394070605943,
    openingHours: { en: "Call ahead before visiting", "zh-Hans": "到访前请先致电" },
    contactPhone: "6732 1286",
    costType: "free",
    languages: ["en", "zh-Hans", "ms", "ta"],
    accessibilityFeatures: [
      { en: "Lift access", "zh-Hans": "有电梯", ms: "Ada lif", ta: "லிப்ட் வசதி" },
      { en: "Step-free entrance", "zh-Hans": "无台阶入口", ms: "Pintu masuk tanpa tangga", ta: "படிக்கட்டு இல்லா நுழைவு" },
    ],
    practicalNotes: [
      { en: "Use the lift to level 4 and look for unit #04-35.", "zh-Hans": "搭电梯到四楼，找 #04-35。" },
    ],
    photos: [],
    verificationStatus: "verified",
    confidenceLevel: "high",
    source: "seed",
    mapProviderReference: "onemap:162008",
    currentHazardStatus: "none",
    details: { type: "senior_activity", activities: ["befriending", "light exercise"], sheltered: true, dropInFriendly: true },
    ...timestamps,
  },
  {
    id: "jalan-kukoh-rc",
    linkedAgencyKey: "jalan_kukoh_rc",
    name: { en: "Jalan Kukoh RC", "zh-Hans": "惹兰古谷居民委员会", ms: "RC Jalan Kukoh" },
    category: "rc_centre",
    description: { en: "Local RC for volunteer help, neighbourhood issues and resident follow-up.", "zh-Hans": "本区居民委员会，可协助义工和社区事项。" },
    address: { en: "Blk 10 Jalan Kukoh, #04-61, Singapore 162010", "zh-Hans": "惹兰古谷 10 座 #04-61，新加坡 162010" },
    latitude: 1.286973834439803,
    longitude: 103.8390758234829,
    openingHours: { en: "Call ahead before visiting", "zh-Hans": "到访前请先致电" },
    contactPhone: "6732 0060",
    languages: ["en", "zh-Hans", "ms"],
    accessibilityFeatures: [{ en: "Lift access", "zh-Hans": "有电梯" }],
    practicalNotes: [{ en: "Ask here for help explaining a case to volunteers.", "zh-Hans": "可在这里请义工协助说明个案。" }],
    photos: [],
    verificationStatus: "needs_recheck",
    confidenceLevel: "medium",
    source: "seed",
    mapProviderReference: "onemap:162010",
    currentHazardStatus: "none",
    details: { type: "rc_centre", services: ["case referral", "form guidance"], volunteerHours: "Call ahead" },
    ...timestamps,
  },
  {
    id: "catchplus-jalan-kukoh",
    linkedAgencyKey: "catchplus_jalan_kukoh",
    name: { en: "CatchPlus Centre", "zh-Hans": "CatchPlus 中心", ms: "Pusat CatchPlus" },
    category: "digital_form_help",
    description: { en: "Community help point for digital forms and practical referrals.", "zh-Hans": "社区支援点，可协助数码表格和实际转介。" },
    address: { en: "10 Jalan Kukoh, #04-55, Singapore 162010", "zh-Hans": "惹兰古谷 10 号 #04-55，新加坡 162010" },
    latitude: 1.286973834439803,
    longitude: 103.8390758234829,
    openingHours: { en: "Call ahead before visiting", "zh-Hans": "到访前请先致电" },
    languages: ["en", "zh-Hans", "ms"],
    accessibilityFeatures: [{ en: "Seated waiting area", "zh-Hans": "有座位等候区" }],
    practicalNotes: [{ en: "Bring your phone, Singpass app, and any letter you received.", "zh-Hans": "请带手机、Singpass 应用和收到的信件。" }],
    photos: [],
    verificationStatus: "needs_recheck",
    confidenceLevel: "medium",
    source: "seed",
    mapProviderReference: "onemap:162010",
    currentHazardStatus: "none",
    details: {
      type: "digital_form_help",
      helpTypes: ["Singpass", "CDC vouchers", "online forms"],
      appointmentRequired: false,
      documentsNeeded: ["phone", "letter", "Singpass app if available"],
      singpassHelpAvailable: true,
      voucherHelpAvailable: true,
    },
    ...timestamps,
  },
  {
    id: "kreta-ayer-community-club",
    linkedAgencyKey: "kreta_ayer_community_club",
    name: { en: "Kreta Ayer Community Club", "zh-Hans": "牛车水民众俱乐部", ms: "Kelab Masyarakat Kreta Ayer" },
    category: "digital_form_help",
    description: { en: "Community club for classes, help counters and adviser-session signposting.", "zh-Hans": "民众俱乐部，可提供课程、服务柜台和接见居民活动指引。" },
    address: { en: "28A Kreta Ayer Road, Singapore 088995", "zh-Hans": "牛车水路 28A 号，新加坡 088995" },
    latitude: 1.281208198577837,
    longitude: 103.8430205222926,
    openingHours: { en: "Call ahead before visiting", "zh-Hans": "到访前请先致电" },
    contactPhone: "6222 3597",
    languages: ["en", "zh-Hans", "ms"],
    accessibilityFeatures: [{ en: "Step-free entrance", "zh-Hans": "无台阶入口" }],
    practicalNotes: [{ en: "Ask the counter for the right help desk or adviser-session timing.", "zh-Hans": "请向柜台询问服务台或接见居民活动时间。" }],
    photos: [],
    verificationStatus: "verified",
    confidenceLevel: "high",
    source: "seed",
    mapProviderReference: "onemap:088995",
    currentHazardStatus: "none",
    details: {
      type: "digital_form_help",
      helpTypes: ["forms", "referrals", "adviser sessions"],
      appointmentRequired: false,
      documentsNeeded: ["letter", "this receipt"],
    },
    ...timestamps,
  },
  {
    id: "active-ageing-centre-chin-swee",
    linkedAgencyKey: "active_ageing_centre_chin_swee",
    name: { en: "Chinatown Active Ageing Centre (Chin Swee)", "zh-Hans": "牛车水乐龄活动中心（振瑞）" },
    category: "senior_activity",
    description: { en: "Secondary nearby active ageing centre around Chin Swee.", "zh-Hans": "振瑞路附近的另一个乐龄活动中心。" },
    address: { en: "51 Chin Swee Road, #04-83, Singapore 160051", "zh-Hans": "振瑞路 51 号 #04-83，新加坡 160051" },
    latitude: 1.287403007915311,
    longitude: 103.8420297788909,
    openingHours: { en: "Call ahead before visiting", "zh-Hans": "到访前请先致电" },
    contactPhone: "6533 3202",
    languages: ["en", "zh-Hans"],
    accessibilityFeatures: [{ en: "Lift access", "zh-Hans": "有电梯" }],
    practicalNotes: [{ en: "A useful backup if the Jalan Kukoh centre is busy.", "zh-Hans": "如果惹兰古谷中心较忙，可考虑这里。" }],
    photos: [],
    verificationStatus: "verified",
    confidenceLevel: "high",
    source: "seed",
    mapProviderReference: "onemap:160051",
    currentHazardStatus: "none",
    details: { type: "senior_activity", activities: ["befriending", "activities"], sheltered: true, dropInFriendly: true },
    ...timestamps,
  },
  {
    id: "jalan-kukoh-pickup",
    name: { en: "Jalan Kukoh Pickup Point", "zh-Hans": "惹兰古谷接送点" },
    category: "pickup_dropoff",
    description: { en: "Sheltered pickup and drop-off point near the kiosk.", "zh-Hans": "服务亭附近的有盖接送点。" },
    address: { en: "Jalan Kukoh service road", "zh-Hans": "惹兰古谷服务路" },
    latitude: 1.28723,
    longitude: 103.8392,
    openingHours: { en: "Always open", "zh-Hans": "全天开放" },
    languages: ["en", "zh-Hans", "ms"],
    accessibilityFeatures: [{ en: "Wheelchair taxi suitable", "zh-Hans": "适合轮椅德士" }],
    practicalNotes: [{ en: "Best pickup point when the void deck is crowded.", "zh-Hans": "组屋楼下较拥挤时可用这个接送点。" }],
    photos: [],
    verificationStatus: "community_submitted",
    confidenceLevel: "medium",
    source: "seed",
    currentHazardStatus: "none",
    details: {
      type: "pickup_dropoff",
      sheltered: true,
      vehicleTypeSupported: ["taxi", "wheelchair taxi", "family car"],
      wheelchairTaxiSuitable: true,
      routeToEntrance: "Use the level walkway back to the kiosk.",
    },
    ...timestamps,
  },
];

function routeSteps(resource: Resource, mode: RouteMode) {
  const destinationName = resource.name.en;
  return [
    {
      id: `${resource.id}-${mode}-step-1`,
      instruction: { en: "Leave the kiosk and follow the sheltered void-deck path.", "zh-Hans": "离开服务亭后，沿着有盖组屋楼下通道前进。" },
      distanceMeters: 60,
      durationMinutes: 1,
      latitude: 1.28733,
      longitude: 103.83928,
    },
    {
      id: `${resource.id}-${mode}-step-2`,
      instruction: { en: `Continue to ${destinationName} and check the lift lobby sign.`, "zh-Hans": "继续前往目的地，并查看电梯厅指示牌。" },
      distanceMeters: 120,
      durationMinutes: 3,
      latitude: resource.latitude,
      longitude: resource.longitude,
    },
  ];
}

function buildRoutes(resource: Resource): RouteOption[] {
  const sharedPolyline = [
    { latitude: kioskLocation.latitude, longitude: kioskLocation.longitude },
    { latitude: (kioskLocation.latitude + resource.latitude) / 2, longitude: (kioskLocation.longitude + resource.longitude) / 2 },
    { latitude: resource.latitude, longitude: resource.longitude },
  ];

  return [
    {
      id: `${resource.id}-wheelchair`,
      destinationResourceId: resource.id,
      mode: "wheelchair",
      durationMinutes: 6,
      distanceMeters: 280,
      isRecommended: true,
      providerLabel: "Wheelchair-friendly fixture fallback",
      origin: kioskLocation,
      polyline: sharedPolyline,
      notes: [{ en: "Seeded fallback route. Confirm ramps and lift status before leaving.", "zh-Hans": "示范备用路线。出发前请确认斜坡和电梯状态。" }],
      steps: routeSteps(resource, "wheelchair"),
    },
    {
      id: `${resource.id}-walk`,
      destinationResourceId: resource.id,
      mode: "walk",
      durationMinutes: 4,
      distanceMeters: 220,
      isRecommended: false,
      providerLabel: "Walking fixture fallback",
      origin: kioskLocation,
      polyline: sharedPolyline,
      notes: [{ en: "Seeded walking route for the demo.", "zh-Hans": "示范步行路线。" }],
      steps: routeSteps(resource, "walk"),
    },
    {
      id: `${resource.id}-drive`,
      destinationResourceId: resource.id,
      mode: "drive",
      durationMinutes: 3,
      distanceMeters: 500,
      isRecommended: false,
      providerLabel: "Driving fixture fallback",
      origin: kioskLocation,
      polyline: sharedPolyline,
      notes: [{ en: "Use nearby service roads for pickup and drop-off.", "zh-Hans": "可使用附近服务路接送。" }],
      steps: routeSteps(resource, "drive"),
    },
  ];
}

export const demoRoutes: Record<string, RouteOption[]> = Object.fromEntries(
  demoResources.map((resource) => [resource.id, buildRoutes(resource)]),
);
