import type { AgencyContact } from "../../types/contracts";

const UPDATED_AT = "2026-05-09T00:00:00+08:00";

export const agencies: AgencyContact[] = [
  {
    key: "hdb_essential_maintenance",
    name: "HDB Essential Maintenance Service Unit",
    hotline: "1800-225-5432",
    category: "housing",
    openingHours: "24 hours for essential maintenance",
    multilingualBlurb: {
      en: "For urgent HDB estate maintenance issues such as lift faults and water leaks.",
      "zh-Hans": "处理紧急组屋维修问题，例如电梯故障和漏水。",
    },
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "hdb_branch_office",
    name: "HDB Branch Office (general enquiries)",
    hotline: "1800-225-5432",
    category: "housing",
    openingHours: "Mon–Fri 8am–5pm",
    multilingualBlurb: {
      en: "General HDB matters: rental, upgrading, mailbox, common-area issues.",
      "zh-Hans": "组屋一般事务：租赁、提升、信箱与公共区域问题。",
    },
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "lta_customer_service",
    name: "Land Transport Authority Customer Service",
    hotline: "1800-225-5582",
    category: "transport",
    openingHours: "Mon–Fri 8.30am–6.30pm, Sat 8.30am–1pm",
    multilingualBlurb: {
      en: "Bus, MRT, taxi and concession-card matters.",
      "zh-Hans": "公交、地铁、德士与乐龄卡相关事宜。",
    },
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "transport_aid_silver_generation",
    name: "Silver Generation Transport Aid",
    category: "transport",
    multilingualBlurb: {
      en: "Subsidised transport help for medical appointments through SGO and partner agencies.",
      "zh-Hans": "通过乐龄助理处与合作机构提供的就医交通资助。",
    },
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "aic_eldercare_hotline",
    name: "Agency for Integrated Care Hotline",
    hotline: "1800-650-6060",
    category: "healthcare",
    openingHours: "Mon–Fri 8.30am–8.30pm, Sat 8.30am–4pm",
    multilingualBlurb: {
      en: "Information on home care, community care, day care and senior support services.",
      "zh-Hans": "查询居家护理、社区护理、日间护理与乐龄支援服务。",
    },
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "scdf_emergency",
    name: "SCDF Emergency Ambulance",
    hotline: "995",
    category: "healthcare",
    openingHours: "24 hours",
    multilingualBlurb: {
      en: "Medical emergencies and ambulance dispatch. Call only for genuine emergencies.",
      "zh-Hans": "医疗紧急情况与救护车调派。仅在真正紧急时拨打。",
    },
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "police_non_emergency",
    name: "Singapore Police Non-Emergency",
    hotline: "1800-255-0000",
    category: "legal",
    openingHours: "24 hours",
    multilingualBlurb: {
      en: "Non-urgent police matters. For emergencies dial 999.",
      "zh-Hans": "非紧急警务事项。如有紧急情况请拨999。",
    },
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "legal_aid_bureau",
    name: "Legal Aid Bureau",
    hotline: "1800-325-1424",
    category: "legal",
    openingHours: "Mon–Fri 8.30am–5pm",
    multilingualBlurb: {
      en: "Civil legal aid for those who qualify on means and merits.",
      "zh-Hans": "为符合经济与案件条件的居民提供民事法律援助。",
    },
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "family_service_centre",
    name: "Family Service Centre (nearest branch)",
    category: "social_services",
    multilingualBlurb: {
      en: "Counselling, family support and social services. Refer to nearest FSC.",
      "zh-Hans": "辅导、家庭支援与社会服务。可前往最靠近的家庭服务中心。",
    },
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "silver_generation_office",
    name: "Silver Generation Office",
    hotline: "1800-650-6060",
    category: "social_services",
    multilingualBlurb: {
      en: "Outreach and information for seniors on schemes and benefits.",
      "zh-Hans": "为乐龄居民提供计划与福利的资讯与上门关怀。",
    },
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "comcare_hotline",
    name: "ComCare Hotline",
    hotline: "1800-222-0000",
    category: "financial_assistance",
    openingHours: "Mon–Fri 8.30am–6pm, Sat 8.30am–1pm",
    multilingualBlurb: {
      en: "Financial assistance for low-income individuals and families.",
      "zh-Hans": "为低收入个人与家庭提供经济援助。",
    },
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "cpf_senior_hotline",
    name: "CPF Senior Helpline",
    hotline: "1800-227-1188",
    category: "financial_assistance",
    openingHours: "Mon–Fri 8am–5.30pm",
    multilingualBlurb: {
      en: "CPF withdrawals, retirement payouts and Medisave matters.",
      "zh-Hans": "公积金提款、退休金与保健储蓄相关事宜。",
    },
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "peoples_association",
    name: "People's Association (Community Centre)",
    hotline: "6225-5322",
    category: "elderly_activity",
    multilingualBlurb: {
      en: "Senior activities, courses and Community Centre programmes.",
      "zh-Hans": "乐龄活动、课程与民众俱乐部项目。",
    },
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "active_ageing_centre",
    name: "Active Ageing Centre (nearest branch)",
    category: "elderly_activity",
    multilingualBlurb: {
      en: "Drop-in centres for seniors offering activities, befriending and light support.",
      "zh-Hans": "乐龄活动中心，提供活动、陪伴与轻度支援服务。",
    },
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "skillsfuture_singapore",
    name: "SkillsFuture Singapore",
    hotline: "6785-5785",
    category: "digital_help",
    openingHours: "Mon–Fri 9am–6pm",
    multilingualBlurb: {
      en: "Digital and skills training, including senior-friendly courses.",
      "zh-Hans": "数码与技能培训，包括乐龄友善课程。",
    },
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "sg_digital_office_seniors_go_digital",
    name: "Seniors Go Digital",
    category: "digital_help",
    multilingualBlurb: {
      en: "1-on-1 help with mobile apps, Singpass and government e-services.",
      "zh-Hans": "提供手机应用、Singpass与政府电子服务的一对一指导。",
    },
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "mp_meet_the_people_session",
    name: "MP Meet-the-People Session",
    category: "mp_meet_the_people",
    openingHours: "Weekly, varies by constituency",
    multilingualBlurb: {
      en: "Weekly session where residents can request help from their elected MP.",
      "zh-Hans": "每周一次的接见居民活动，可向民选议员寻求协助。",
    },
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "rc_visit",
    name: "Residents' Committee Visit",
    category: "rc_visit",
    multilingualBlurb: {
      en: "Local Residents' Committee volunteers can follow up on neighbourhood and welfare matters.",
      "zh-Hans": "居民委员会志工可跟进社区与福利相关事宜。",
    },
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
];
